baseURL = 'https://mdinata.my.id/'
languageCode = 'en-us'
title = 'Hendra Manudinata'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi there! ðŸ‘‹'
homeIntroContent = """
I'm **Hendra Manudinata**, usually called **Hendra**.
I'm a student from Indonesia with interests in web development,
embedded devices, as well as cyber security.
I'm currently pursuing a bachelor's degree in [Information Technology](https://www.its.ac.id/it)
at [Institut Teknologi Sepuluh Nopember](https://www.its.ac.id).

I tinker with Android, Linux, IoT, and embedded devices, but now I mostly work on
web applications. My [GitHub](https://github.com/manoedinata) and [GitLab](https://github.com/manoedinata)
page is where I store majority of my work. I usually made my projects FOSS,
and occasionally contributes to other open-source projects.

I'm also interested in robotics. I'm currently taking part as a programmer in
[IRIS ITS](https://iris.its.ac.id), a research & development team for wheeled robot soccer competitions,
such as [FIRA RoboWorld Cup](https://firaworldcup.org), [RoboCup](https://www.robocup.org),
and Indonesia's [Kontes Robot Indonesia](https://kontesrobotindonesia.id).
"""

# Collection to display on home
homeCollectionTitle = 'Blogs'
homeCollection = 'blogs'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/manoedinata/"

[[params.social]]
name = "github"
url = "https://github.com/manoedinata"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blogs"
url = "/blogs"

[[params.menu]]
name = "cv"
url = "/CV/"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
noClasses = false

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[[cascade]]
  [cascade.params]
    toc = false
    readTime = true
    autonumber = true
    math = false

  [cascade._target]
    path = "/blogs/**"
