backend:
  name: github
  repo: manoedinata/manoedinata.github.io
  branch: master

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "blogs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blogs" # Used in the UI, ie.: "New Post"
    folder: "content/blogs" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - { label: Site Title for Browser Tab, name: title, widget: string }
